#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#    Mar 21, 2019 10:41:29 PM CET  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global entry1, entry2, entry3, entry4, entry5, entry6, entry7
    global var1, var2
    entry1 = tk.StringVar()
    entry2 = tk.StringVar()
    entry3 = tk.StringVar()
    entry4 = tk.StringVar()
    entry5 = tk.StringVar()
    entry6 = tk.StringVar()
    entry7 = tk.StringVar()
    var1 = tk.StringVar()
    var2 = tk.StringVar()
    entry1.set('0')
    entry2.set('3')
    entry3.set('2')
    entry4.set('1')
    entry5.set('200')
    entry6.set('0.5')
    entry7.set('1')

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Form
    Form.vp_start_gui()




